---
entry:
  name_length_max: 5
  position_default: -1
  prefer_in_dir_conflict: new
  prefer_in_name_conflict: new
file:
  backup: places.bak.yml
  data: places.yml
  return: last_choice
list:
  deprecate_bin: 1209600
  deprecate_new: 1209600
  name_default: use
  sort_default: position
  sorted_by: current
  special_comment:
    all: all
    bin: bin
    named: ''
    new: new
    stale: stale
  special_name:
    all: all
    bin: bin
    named: named
    new: new
    stale: stale
  start_with: current
syntax:
  command_shortcut:
    add: a
    copy: c
    delete: d
    dir: D
    edit: e
    help: h
    list: l
    list-add: l-a
    list-delete: l-d
    list-description: l-D
    list-lists: l-l
    list-name: l-n
    list-special: l-s
    move: m
    name: n
    remove: r
    sort: s
  option_shortcut:
    help:
      basics: b
      commands: c
      install: i
      settings: s
    sort:
      created: c
      dir: D
      last_visit: l
      name: n
      position: p
      visits: v
  sigil:
    command: '-'
    entry_name: ':'
    entry_position: '^'
    help: '?'
    special_entry: +
    special_list: '@'
    target_entry: '>'
  special_entry:
    last: _
    previous: '-'
