---
entry:
  dir_exists: 1
  dir_move: 1
  name_length_max: 5
  position_default: -1
  prefer_in_dir_conflict: new
  prefer_in_name_conflict: new
file:
  backup: places.bak.yml
  data: places.yml
  return: last_choice
list:
  deprecate_bin: 1209600
  deprecate_new: 1209600
  name_default: use
  name_length_max: 6
  sort_default: position
  sorted_by: current
  special_description:
    all: 'all entries, even deleted ones'
    bin: recycling bin of deleted entries
    named: entries with names
    new: recently created entries
    stale: entries with not existing directories
  special_name:
    all: all
    bin: bin
    named: named
    new: new
    stale: stale
  start_with: current
syntax:
  command_shortcut:
    add: a
    copy: c
    delete: d
    dir: D
    help: h
    list: l
    list-add: l-a
    list-delete: l-d
    list-description: l-D
    list-lists: l-l
    list-name: l-N
    list-special: l-s
    move: m
    name: N
    redir: R
    remove: r
    script: S
    sort: s
    undelete: u
  option_shortcut:
    help:
      basics: b
      commands: c
      install: i
      settings: s
    sort:
      created: c
      dir: D
      last_visit: l
      name: n
      position: p
      script: S
      visits: v
  sigil:
    command: '-'
    entry_name: ':'
    entry_position: '^'
    file: <
    help: '?'
    special_entry: +
    special_list: '@'
    target_entry: '>'
  special_entry:
    last: _
    previous: '-'
